//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment4
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShowDetail
    {
        public int ShowDetailKey { get; set; }
        public Nullable<int> ShowKey { get; set; }
        public Nullable<int> ArtistKey { get; set; }
        public System.TimeSpan ShowDetailArtistStartTime { get; set; }
        public string ShowDetailAdditional { get; set; }
    
        public virtual Artist Artist { get; set; }
        public virtual Show Show { get; set; }
    }
}
