//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment4
{
    using System;
    using System.Collections.Generic;
    
    public partial class VenueLogin
    {
        public int VenueLoginKey { get; set; }
        public Nullable<int> VenueKey { get; set; }
        public string VenueLoginUserName { get; set; }
        public string VenueLoginPasswordPlain { get; set; }
        public int VenueLoginRandom { get; set; }
        public byte[] VenueLoginHashed { get; set; }
        public Nullable<System.DateTime> VenueLoginDateAdded { get; set; }
    
        public virtual Venue Venue { get; set; }
    }
}
