//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fan
    {
        public Fan()
        {
            this.FanLogins = new HashSet<FanLogin>();
        }
    
        public int FanKey { get; set; }
        public string FanName { get; set; }
        public string FanEmail { get; set; }
        public Nullable<System.DateTime> FanDateEntered { get; set; }
    
        public virtual ICollection<FanLogin> FanLogins { get; set; }
    }
}
