//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class FanLogin
    {
        public int FanLoginKey { get; set; }
        public Nullable<int> FanKey { get; set; }
        public string FanLoginUserName { get; set; }
        public string FanLoginPasswordPlain { get; set; }
        public int FanLoginRandom { get; set; }
        public byte[] FanLoginHashed { get; set; }
        public Nullable<System.DateTime> FanLoginDateAdded { get; set; }
    
        public virtual Fan Fan { get; set; }
    }
}
