//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artist
    {
        public Artist()
        {
            this.ShowDetails = new HashSet<ShowDetail>();
        }
    
        public int ArtistKey { get; set; }
        public string ArtistName { get; set; }
        public string ArtistEmail { get; set; }
        public string ArtistWebPage { get; set; }
        public Nullable<System.DateTime> ArtistDateEntered { get; set; }
    
        public virtual ICollection<ShowDetail> ShowDetails { get; set; }
    }
}
