//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venue
    {
        public Venue()
        {
            this.Shows = new HashSet<Show>();
        }
    
        public int VenueKey { get; set; }
        public string VenueName { get; set; }
        public string VenueAddress { get; set; }
        public string VenueCity { get; set; }
        public string VenueState { get; set; }
        public string VenueZipCode { get; set; }
        public string VenuePhone { get; set; }
        public string VenueEmail { get; set; }
        public string VenueWebPage { get; set; }
        public Nullable<int> VenueAgeRestriction { get; set; }
        public Nullable<System.DateTime> VenueDateAdded { get; set; }
    
        public virtual ICollection<Show> Shows { get; set; }
    }
}
