//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment5.Assignment5 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Artist", Namespace="http://schemas.datacontract.org/2004/07/WebApplication1")]
    [System.SerializableAttribute()]
    public partial class Artist : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ArtistDateEnteredField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ArtistEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ArtistKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ArtistNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ArtistWebPageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Assignment5.Assignment5.ShowDetail[] ShowDetailsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ArtistDateEntered {
            get {
                return this.ArtistDateEnteredField;
            }
            set {
                if ((this.ArtistDateEnteredField.Equals(value) != true)) {
                    this.ArtistDateEnteredField = value;
                    this.RaisePropertyChanged("ArtistDateEntered");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ArtistEmail {
            get {
                return this.ArtistEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.ArtistEmailField, value) != true)) {
                    this.ArtistEmailField = value;
                    this.RaisePropertyChanged("ArtistEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ArtistKey {
            get {
                return this.ArtistKeyField;
            }
            set {
                if ((this.ArtistKeyField.Equals(value) != true)) {
                    this.ArtistKeyField = value;
                    this.RaisePropertyChanged("ArtistKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ArtistName {
            get {
                return this.ArtistNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ArtistNameField, value) != true)) {
                    this.ArtistNameField = value;
                    this.RaisePropertyChanged("ArtistName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ArtistWebPage {
            get {
                return this.ArtistWebPageField;
            }
            set {
                if ((object.ReferenceEquals(this.ArtistWebPageField, value) != true)) {
                    this.ArtistWebPageField = value;
                    this.RaisePropertyChanged("ArtistWebPage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Assignment5.Assignment5.ShowDetail[] ShowDetails {
            get {
                return this.ShowDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.ShowDetailsField, value) != true)) {
                    this.ShowDetailsField = value;
                    this.RaisePropertyChanged("ShowDetails");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ShowDetail", Namespace="http://schemas.datacontract.org/2004/07/WebApplication1")]
    [System.SerializableAttribute()]
    public partial class ShowDetail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Assignment5.Assignment5.Artist ArtistField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ArtistKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Assignment5.Assignment5.Show ShowField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShowDetailAdditionalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan ShowDetailArtistStartTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ShowDetailKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ShowKeyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Assignment5.Assignment5.Artist Artist {
            get {
                return this.ArtistField;
            }
            set {
                if ((object.ReferenceEquals(this.ArtistField, value) != true)) {
                    this.ArtistField = value;
                    this.RaisePropertyChanged("Artist");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ArtistKey {
            get {
                return this.ArtistKeyField;
            }
            set {
                if ((this.ArtistKeyField.Equals(value) != true)) {
                    this.ArtistKeyField = value;
                    this.RaisePropertyChanged("ArtistKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Assignment5.Assignment5.Show Show {
            get {
                return this.ShowField;
            }
            set {
                if ((object.ReferenceEquals(this.ShowField, value) != true)) {
                    this.ShowField = value;
                    this.RaisePropertyChanged("Show");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShowDetailAdditional {
            get {
                return this.ShowDetailAdditionalField;
            }
            set {
                if ((object.ReferenceEquals(this.ShowDetailAdditionalField, value) != true)) {
                    this.ShowDetailAdditionalField = value;
                    this.RaisePropertyChanged("ShowDetailAdditional");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan ShowDetailArtistStartTime {
            get {
                return this.ShowDetailArtistStartTimeField;
            }
            set {
                if ((this.ShowDetailArtistStartTimeField.Equals(value) != true)) {
                    this.ShowDetailArtistStartTimeField = value;
                    this.RaisePropertyChanged("ShowDetailArtistStartTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ShowDetailKey {
            get {
                return this.ShowDetailKeyField;
            }
            set {
                if ((this.ShowDetailKeyField.Equals(value) != true)) {
                    this.ShowDetailKeyField = value;
                    this.RaisePropertyChanged("ShowDetailKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ShowKey {
            get {
                return this.ShowKeyField;
            }
            set {
                if ((this.ShowKeyField.Equals(value) != true)) {
                    this.ShowKeyField = value;
                    this.RaisePropertyChanged("ShowKey");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Show", Namespace="http://schemas.datacontract.org/2004/07/WebApplication1")]
    [System.SerializableAttribute()]
    public partial class Show : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ShowDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ShowDateEnteredField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Assignment5.Assignment5.ShowDetail[] ShowDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ShowKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShowNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShowTicketInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan ShowTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Assignment5.Assignment5.Venue VenueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> VenueKeyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ShowDate {
            get {
                return this.ShowDateField;
            }
            set {
                if ((this.ShowDateField.Equals(value) != true)) {
                    this.ShowDateField = value;
                    this.RaisePropertyChanged("ShowDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ShowDateEntered {
            get {
                return this.ShowDateEnteredField;
            }
            set {
                if ((this.ShowDateEnteredField.Equals(value) != true)) {
                    this.ShowDateEnteredField = value;
                    this.RaisePropertyChanged("ShowDateEntered");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Assignment5.Assignment5.ShowDetail[] ShowDetails {
            get {
                return this.ShowDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.ShowDetailsField, value) != true)) {
                    this.ShowDetailsField = value;
                    this.RaisePropertyChanged("ShowDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ShowKey {
            get {
                return this.ShowKeyField;
            }
            set {
                if ((this.ShowKeyField.Equals(value) != true)) {
                    this.ShowKeyField = value;
                    this.RaisePropertyChanged("ShowKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShowName {
            get {
                return this.ShowNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ShowNameField, value) != true)) {
                    this.ShowNameField = value;
                    this.RaisePropertyChanged("ShowName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShowTicketInfo {
            get {
                return this.ShowTicketInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.ShowTicketInfoField, value) != true)) {
                    this.ShowTicketInfoField = value;
                    this.RaisePropertyChanged("ShowTicketInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan ShowTime {
            get {
                return this.ShowTimeField;
            }
            set {
                if ((this.ShowTimeField.Equals(value) != true)) {
                    this.ShowTimeField = value;
                    this.RaisePropertyChanged("ShowTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Assignment5.Assignment5.Venue Venue {
            get {
                return this.VenueField;
            }
            set {
                if ((object.ReferenceEquals(this.VenueField, value) != true)) {
                    this.VenueField = value;
                    this.RaisePropertyChanged("Venue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> VenueKey {
            get {
                return this.VenueKeyField;
            }
            set {
                if ((this.VenueKeyField.Equals(value) != true)) {
                    this.VenueKeyField = value;
                    this.RaisePropertyChanged("VenueKey");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Venue", Namespace="http://schemas.datacontract.org/2004/07/WebApplication1")]
    [System.SerializableAttribute()]
    public partial class Venue : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Assignment5.Assignment5.Show[] ShowsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VenueAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> VenueAgeRestrictionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VenueCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> VenueDateAddedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VenueEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VenueKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VenueNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VenuePhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VenueStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VenueWebPageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VenueZipCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Assignment5.Assignment5.Show[] Shows {
            get {
                return this.ShowsField;
            }
            set {
                if ((object.ReferenceEquals(this.ShowsField, value) != true)) {
                    this.ShowsField = value;
                    this.RaisePropertyChanged("Shows");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VenueAddress {
            get {
                return this.VenueAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.VenueAddressField, value) != true)) {
                    this.VenueAddressField = value;
                    this.RaisePropertyChanged("VenueAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> VenueAgeRestriction {
            get {
                return this.VenueAgeRestrictionField;
            }
            set {
                if ((this.VenueAgeRestrictionField.Equals(value) != true)) {
                    this.VenueAgeRestrictionField = value;
                    this.RaisePropertyChanged("VenueAgeRestriction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VenueCity {
            get {
                return this.VenueCityField;
            }
            set {
                if ((object.ReferenceEquals(this.VenueCityField, value) != true)) {
                    this.VenueCityField = value;
                    this.RaisePropertyChanged("VenueCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> VenueDateAdded {
            get {
                return this.VenueDateAddedField;
            }
            set {
                if ((this.VenueDateAddedField.Equals(value) != true)) {
                    this.VenueDateAddedField = value;
                    this.RaisePropertyChanged("VenueDateAdded");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VenueEmail {
            get {
                return this.VenueEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.VenueEmailField, value) != true)) {
                    this.VenueEmailField = value;
                    this.RaisePropertyChanged("VenueEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VenueKey {
            get {
                return this.VenueKeyField;
            }
            set {
                if ((this.VenueKeyField.Equals(value) != true)) {
                    this.VenueKeyField = value;
                    this.RaisePropertyChanged("VenueKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VenueName {
            get {
                return this.VenueNameField;
            }
            set {
                if ((object.ReferenceEquals(this.VenueNameField, value) != true)) {
                    this.VenueNameField = value;
                    this.RaisePropertyChanged("VenueName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VenuePhone {
            get {
                return this.VenuePhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.VenuePhoneField, value) != true)) {
                    this.VenuePhoneField = value;
                    this.RaisePropertyChanged("VenuePhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VenueState {
            get {
                return this.VenueStateField;
            }
            set {
                if ((object.ReferenceEquals(this.VenueStateField, value) != true)) {
                    this.VenueStateField = value;
                    this.RaisePropertyChanged("VenueState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VenueWebPage {
            get {
                return this.VenueWebPageField;
            }
            set {
                if ((object.ReferenceEquals(this.VenueWebPageField, value) != true)) {
                    this.VenueWebPageField = value;
                    this.RaisePropertyChanged("VenueWebPage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VenueZipCode {
            get {
                return this.VenueZipCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.VenueZipCodeField, value) != true)) {
                    this.VenueZipCodeField = value;
                    this.RaisePropertyChanged("VenueZipCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Assignment5.IAddShowService")]
    public interface IAddShowService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddShowService/AddArtist", ReplyAction="http://tempuri.org/IAddShowService/AddArtistResponse")]
        bool AddArtist(Assignment5.Assignment5.Artist a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddShowService/AddArtist", ReplyAction="http://tempuri.org/IAddShowService/AddArtistResponse")]
        System.Threading.Tasks.Task<bool> AddArtistAsync(Assignment5.Assignment5.Artist a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddShowService/AddShow", ReplyAction="http://tempuri.org/IAddShowService/AddShowResponse")]
        bool AddShow(Assignment5.Assignment5.Show s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddShowService/AddShow", ReplyAction="http://tempuri.org/IAddShowService/AddShowResponse")]
        System.Threading.Tasks.Task<bool> AddShowAsync(Assignment5.Assignment5.Show s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddShowService/AddShowDetail", ReplyAction="http://tempuri.org/IAddShowService/AddShowDetailResponse")]
        bool AddShowDetail(Assignment5.Assignment5.Show s, Assignment5.Assignment5.Venue v, Assignment5.Assignment5.ShowDetail sd, Assignment5.Assignment5.Artist a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddShowService/AddShowDetail", ReplyAction="http://tempuri.org/IAddShowService/AddShowDetailResponse")]
        System.Threading.Tasks.Task<bool> AddShowDetailAsync(Assignment5.Assignment5.Show s, Assignment5.Assignment5.Venue v, Assignment5.Assignment5.ShowDetail sd, Assignment5.Assignment5.Artist a);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAddShowServiceChannel : Assignment5.Assignment5.IAddShowService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AddShowServiceClient : System.ServiceModel.ClientBase<Assignment5.Assignment5.IAddShowService>, Assignment5.Assignment5.IAddShowService {
        
        public AddShowServiceClient() {
        }
        
        public AddShowServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AddShowServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AddShowServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AddShowServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool AddArtist(Assignment5.Assignment5.Artist a) {
            return base.Channel.AddArtist(a);
        }
        
        public System.Threading.Tasks.Task<bool> AddArtistAsync(Assignment5.Assignment5.Artist a) {
            return base.Channel.AddArtistAsync(a);
        }
        
        public bool AddShow(Assignment5.Assignment5.Show s) {
            return base.Channel.AddShow(s);
        }
        
        public System.Threading.Tasks.Task<bool> AddShowAsync(Assignment5.Assignment5.Show s) {
            return base.Channel.AddShowAsync(s);
        }
        
        public bool AddShowDetail(Assignment5.Assignment5.Show s, Assignment5.Assignment5.Venue v, Assignment5.Assignment5.ShowDetail sd, Assignment5.Assignment5.Artist a) {
            return base.Channel.AddShowDetail(s, v, sd, a);
        }
        
        public System.Threading.Tasks.Task<bool> AddShowDetailAsync(Assignment5.Assignment5.Show s, Assignment5.Assignment5.Venue v, Assignment5.Assignment5.ShowDetail sd, Assignment5.Assignment5.Artist a) {
            return base.Channel.AddShowDetailAsync(s, v, sd, a);
        }
    }
}
